{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Erros e Exceções\n",
    "\n",
    "Erros e exceções são muito importantes no desenvolvimento de uma aplicação, pois eles dizem ao usuário se algo não saiu como esperado, ou para o desenvolvedor se algo está errado, nessa seção aprenderemos sobre *Stack Tracing (\"Análise da Stack\")*, conheceremos os erros nativos da linguagem, aprenderemos a criar nosso próprios erros e veremos sobre *depuração (debugging)*.\n",
    "\n",
    "Mas antes devo explicar qual a diferença entre *Erro* e *Exceção*.\n",
    "\n",
    "***O que seria um Erro?***\n",
    "\n",
    "> Um erro é todo e quaisquer problema que impede a execução do programa.\n",
    "\n",
    "Geralmente ocorrem em tempo de compilação, em Python o único erro possível é o de se *Sintaxe*.\n",
    "\n",
    "Você geralmente não lida com erros e eles são irreversíveis, então geralmente quando eles ocorrem a aplicação é terminada.\n",
    "\n",
    "***O que seria uma Exceção?***\n",
    "\n",
    "> Uma exceção é um tipo de erro que ocorre em tempo de execução\n",
    "\n",
    "Normalmente são erros do próprio programador durante o desenvolvimento, eles não finalizam o programa, mas podem trazer comportamento inexperado para a aplicação.\n",
    "\n",
    "Geralmente são chamados de *Erros lógicos*.\n",
    "\n",
    "## Stack Tracing (\"Análise da Stack\")\n",
    "\n",
    "Stack Tracing consiste em analisar a saída do terminal em busca da origem do erro, essa saida também pode ser chamada de *\"Stack Backtrace\"* ou *\"Stack Traceback\"*.\n",
    "\n",
    "considere o seguinte código:\n",
    "\n",
    "***(Este código resultará em um erro)***"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def a():\n",
    "    i = 0\n",
    "    j = b(i)\n",
    "    return j\n",
    "\n",
    "def b(z):\n",
    "    k = 5\n",
    "    if z == 0:\n",
    "        c()\n",
    "    return k + z\n",
    "\n",
    "def c():\n",
    "    error()\n",
    "\n",
    "a()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "executando este código temos a seguinte saida:\n",
    "\n",
    "```\n",
    "Traceback (most recent call last):\n",
    "  File \"tb.py\", line 15, in <module>\n",
    "    a()\n",
    "  File \"tb.py\", line 3, in a\n",
    "    j = b(i)\n",
    "  File \"tb.py\", line 9, in b\n",
    "    c()\n",
    "  File \"tb.py\", line 13, in c\n",
    "    error()\n",
    "NameError: name 'error' is not defined\n",
    "```\n",
    "\n",
    "vamos \"desmembrar\" essa saida para podermos fazer a análise.\n",
    "\n",
    "temos 3 elementos principais:\n",
    "\n",
    "- O indicador de traceback\n",
    "- A arvore de chamadas (CallStack)\n",
    "- O erro que iniciou todo o processo de traceback e seu tipo.\n",
    "\n",
    "O indicador de traceback diz que as proximas linhas fazem referencia a um traceback, ele é facilmente indentificado por normalmente constar palavras e sentenças como \"Stack Trace\", \"Traceback\", \"Panicked\", \"Panicking\", etc.\n",
    "\n",
    "no nosso exemplo ele seria a primeira linha: `Traceback (most recent call last)`.\n",
    "\n",
    "esse *\"most recent call last\"* diz que a ultima chamada da CallStack é a mais recente.\n",
    "\n",
    "---\n",
    "\n",
    "A arvore de chamadas contém a ordem que os elementos foram executados até chegar ao erro, observemos nosso exemplo:\n",
    "\n",
    "```\n",
    "File \"tb.py\", line 15, in <module>\n",
    "  a()\n",
    "File \"tb.py\", line 3, in a\n",
    "  j = b(i)\n",
    "File \"tb.py\", line 9, in b\n",
    "  c()\n",
    "File \"tb.py\", line 13, in c\n",
    "  error()\n",
    "```\n",
    "\n",
    "O erro foi acionado na função `c` presente na linha 13, que por sua vez foi chamada pela função `b` na linha 9, que então foi chamada pela função `a` na linha 3, que por fim foi executada na linha 15 diretamente no arquivo.\n",
    "\n",
    "perceba que nós temos um passo-a-passo de chamadas até indentificarmos a origem do erro. Isso se torna excepcionalmente útil para descobrirmos a origem de um erro.\n",
    "\n",
    "---\n",
    "\n",
    "E por fim o erro que iniciou todo esse processo se encontra ao final da traceback: `NameError: name 'error' is not defined`\n",
    "\n",
    "perceba que ele além de conter o erro, contém também seu tipo, que no nosso caso é um `NameError`, isso é bastante importante e útil para sabermos como consertar, pois sabendo o tipo de erro/exceção poderemos pensar na melhor solução para o problema, além de podermos lidar com ele usando um bloco `try-except`, que veremos mais a frente.\n",
    "\n",
    "## Erros e exceções nativas\n",
    "\n",
    "Esses erros e exceções já estão presentes e definidos na linguagem, são erros comuns e genéricos, normalmente associados a questões da linguagem mesmo. Antes de prover uma lista com os mais comuns/úteis, devo explicar a heirarquia de erros.\n",
    "\n",
    "Todas as exceções em Python são classes que herdam caracteristicas de 5 classes base, sendo essas as classes:\n",
    "\n",
    "- `BaseException`\n",
    "- `Exception`\n",
    "- `ArithmeticError`\n",
    "- `BufferError`\n",
    "- `LookupError`\n",
    "\n",
    "### BaseExeption\n",
    "\n",
    "Essa classe é a base de todas as outras exceções e erros em Python e ***NÃO*** deve ser usada como base para exceções definidas pelo usuário, pois exceções que são baseadas nesta normalmente são associadas com terminar o programa, ou seja, se tivermos erros do usuário baseados nela e nós lidarmos com esses erros, podemos acidentalmente impedir que o programa possa ser finalizado por exemplo.\n",
    "\n",
    "### Exception\n",
    "\n",
    "Essa é a classe base para todas as exceções que não terminam com a execução do programa e todos os erros definidos pelo usuário também devem herdar desta classe.\n",
    "\n",
    "### ArithmeticError\n",
    "\n",
    "Essa é a classe base para todas as exceções que lidam com erros artiméticos.\n",
    "\n",
    "### BufferError\n",
    "\n",
    "Essa exceção é usada quando temos algum problema envolvendo operações com buffers\n",
    "\n",
    "### LookupError\n",
    "\n",
    "Base para todos os erros que envolvem mapeamento inválido de chaves ou indexes.\n",
    "\n",
    "## Hierarquia de Exceções\n",
    "\n",
    "- BaseException\n",
    "  - SystemExit\n",
    "  - KeyboardInterrupt\n",
    "  - GeneratorExit\n",
    "  - Exception\n",
    "    - StopIteration\n",
    "    - StopAsyncIteration\n",
    "    - ArithmeticError\n",
    "      - FloatingPointError\n",
    "      - OverflowError\n",
    "      - ZeroDivisionError\n",
    "    - AssertionError\n",
    "    - AttributeError\n",
    "    - BufferError\n",
    "    - EOFError\n",
    "    - ImportError\n",
    "      - ModuleNotFoundError\n",
    "    - LookupError\n",
    "      - IndexError\n",
    "      - KeyError\n",
    "    - MemoryError\n",
    "    - NameError\n",
    "      - UnboundLocalError\n",
    "    - OSError\n",
    "      - BlockingIOError\n",
    "      - ChildProcessError\n",
    "      - ConnectionError\n",
    "        - BrokenPipeError\n",
    "        - ConnectionAbortedError\n",
    "        - ConnectionRefusedError\n",
    "        - ConnectionResetError\n",
    "      - FileExistsError\n",
    "      - FileNotFoundError\n",
    "      - InterruptedError\n",
    "      - IsADirectoryError\n",
    "      - NotADirectoryError\n",
    "      - PermissionError\n",
    "      - ProcessLookupError\n",
    "      - TimeoutError\n",
    "    - ReferenceError\n",
    "    - RuntimeError\n",
    "      - NotImplementedError\n",
    "      - RecursionError\n",
    "    - SyntaxError\n",
    "      - IndentationError\n",
    "        - TabError\n",
    "    - SystemError\n",
    "    - TypeError\n",
    "    - ValueError\n",
    "      - UnicodeError\n",
    "        - UnicodeDecodeError\n",
    "        - UnicodeEncodeError\n",
    "        - UnicodeTranslateError\n",
    "    - Warning\n",
    "      - DeprecationWarning\n",
    "      - PendingDeprecationWarning\n",
    "      - RuntimeWarning\n",
    "      - SyntaxWarning\n",
    "      - UserWarning\n",
    "      - FutureWarning\n",
    "      - ImportWarning\n",
    "      - UnicodeWarning\n",
    "      - BytesWarning\n",
    "      - EncodingWarning\n",
    "      - ResourceWarning\n",
    "\n",
    "Irei explicar cada erro, se você não entender de cara, tudo bem, existem erros sobre questões mais avançadas como corrotinas, entre outras, isso servirá mais como um guia consultas futuras."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## SystemExit\n",
    "\n",
    "Esta exceção é levantada pela função `sys.exit()`. Ele herda de `BaseException` em vez de `Exception` para que não seja acidentalmente capturado pelo código que captura `Exception`. Isso permite que a exceção se propague corretamente e faça com que o interpretador saia. Quando não é tratado, o interpretador Python sai e nenhum traceback é impresso. \n",
    "\n",
    "O construtor aceita o mesmo argumento opcional passado para `sys.exit()`. Se o valor for um inteiro, ele especifica o status de saída do sistema; se for `None`, o status de saída é 0; se tiver outro tipo (como uma string), o valor do objeto é exibido e o status de saída é 1.\n",
    "\n",
    "## KeyboardInterrupt\n",
    "\n",
    "Levantada quando um usuário aperta a tecla de interrupção (normalmente Control-C ou Delete). Durante a execução, uma checagem de interrupção é feita regularmente. A exceção herda de `BaseException` para que não seja capturada acidentalmente por códigos que tratam `Exception` e assim evita que o interpretador saia.\n",
    "\n",
    "## GeneratorExit\n",
    "\n",
    "Levantado quando um gerador ou uma corrotina está fechado(a). Herda diretamente de `BaseException` em vez de `Exception`, já que tecnicamente não é um erro.\n",
    "\n",
    "### StopIteration\n",
    "\n",
    "Levantada pela função embutida `next()` e o método `__next__()` de um iterador para sinalizar que não há mais itens produzidos pelo iterador.\n",
    "\n",
    "O objeto exceção tem um único atributo `value`, que é fornecido como um argumento ao construir a exceção, e o padrão é `None`.\n",
    "\n",
    "Quando uma função geradora ou corrotina retorna, uma nova instância `StopIteration` é levantada, e o valor retornado pela função é usado como o parâmetro `value` para o construtor da exceção.\n",
    "\n",
    "Se um código gerador direta ou indiretamente levantar `StopIteration`, ele é convertido em uma `RuntimeError` (mantendo o `StopIteration` como a nova causa da exceção).\n",
    "\n",
    "### StopAsyncIteration\n",
    "\n",
    "Deve ser levantada pelo método `__anext__()` de um objeto iterador assíncrono para parar a iteração.\n",
    "\n",
    "#### FloatingPointError\n",
    "\n",
    "Não usado atualmente.\n",
    "\n",
    "#### OverflowError\n",
    "\n",
    "Levantada quando o resultado de uma operação aritmética é muito grande para ser representada. Para inteiros normalmente se é levantado `MemoryError`.\n",
    "\n",
    "#### ZeroDivisionError\n",
    "\n",
    "Levantada quando o segundo argumento de uma divisão ou operação de módulo é zero. O valor associado é uma string que indica o tipo dos operandos e a operação.\n",
    "\n",
    "### AssertionError\n",
    "\n",
    "Levantado quando uma instrução `assert` falha.\n",
    "\n",
    "### AttributeError\n",
    "\n",
    "Levantado quando uma referência de atributo ou atribuição falha. (Quando um objeto não oferece suporte a referências ou atribuições de atributos, TypeError é levantado.)\n",
    "\n",
    "### BufferError\n",
    "\n",
    "Levantado quando uma operação relacionada a buffer não puder ser realizada.\n",
    "\n",
    "### EOFError\n",
    "\n",
    "Levantado quando a função `input()` atinge uma condição de fim de arquivo (EOF) sem ler nenhum dado.\n",
    "\n",
    "### ImportError\n",
    "\n",
    "Levantada quando a instrução `import` tem problemas ao tentar carregar um módulo. Também é gerado quando o `“from list”` em `from ... import` tem um nome que não pode ser encontrado.\n",
    "\n",
    "#### ModuleNotFoundError\n",
    "\n",
    "Uma subclasse de `ImportError` que é levantada por `import` quando um módulo não pôde ser localizado. Também é levantada quando `None` é encontrado em `sys.modules`.\n",
    "\n",
    "#### IndexError\n",
    "\n",
    "Levantada quando um índice de alguma sequência está fora do intervalo. (Índices de fatia são truncados silenciosamente para cair num intervalo permitido; se um índice não for um inteiro, TypeError é levantada.)\n",
    "\n",
    "#### KeyError\n",
    "\n",
    "Levantada quando uma chave de mapeamento (dicionário) não é encontrada no conjunto de chaves existentes.\n",
    "\n",
    "### MemoryError\n",
    "\n",
    "Levantada quando uma operação fica sem memória mas a situação ainda pode ser recuperada (excluindo alguns objetos). O valor associado é uma string que indica o tipo de operação (interna) que ficou sem memória.\n",
    "\n",
    "### NameError\n",
    "\n",
    "Levantada quando um nome local ou global não é encontrado. Isso se aplica apenas a nomes não qualificados. O valor associado é uma mensagem de erro que inclui o nome que não pode ser encontrado.\n",
    "\n",
    "#### UnboundLocalError\n",
    "\n",
    "Levantada quando uma referência é feita a uma variável local em uma função ou método, mas nenhum valor foi vinculado a essa variável. Esta é uma subclasse de `NameError`.\n",
    "\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### OSError\n",
    "\n",
    "Esta exceção é levantada quando uma função do sistema retorna um erro relacionado ao sistema, incluindo falhas do tipo E/S como \"arquivo não encontrado\" ou \"disco cheio\" (não para tipos de argumentos não permitidos ou outro erro acessório).\n",
    "\n",
    "#### BlockingIOError\n",
    "\n",
    "Levantada quando uma operação irá bloquear um objeto (ex: soquete) que está configurado para modo de \"não-bloqueio\"\n",
    "\n",
    "#### ChildProcessError\n",
    "\n",
    "Levantada quando uma operação em um processo filho retorna um erro.\n",
    "\n",
    "#### ConnectionError\n",
    "\n",
    "Uma classe base para problemas relacionados à conexão\n",
    "\n",
    "##### BrokenPipeError\n",
    "\n",
    "Levantado quando tentamos escrever em uma conexão onde a outra ponta está fechada, quando o soquete está fechado somente para escrita.\n",
    "\n",
    "##### ConnectionAbortedError\n",
    "\n",
    "Levantado quando uma tentativa de conexão é abortada pelo par.\n",
    "\n",
    "##### ConnectionRefusedError\n",
    "\n",
    "Levantado quando uma tentativa de conexão é recusada pelo par.\n",
    "\n",
    "##### ConnectionResetError\n",
    "\n",
    "Levantado quando uma tentativa de conexão é reiniciada pelo par.\n",
    "\n",
    "#### FileExistsError\n",
    "\n",
    "Levantado quando tenta-se criar um diretorio ou arquivo existente.\n",
    "\n",
    "#### FileNotFoundError\n",
    "\n",
    "Levantado quando um diretorio ou arquivo requisitado não existe. \n",
    "\n",
    "#### InterruptedError\n",
    "\n",
    "Levantada quando uma chamada do sistema é interrompida por um sinal de entrada.\n",
    "\n",
    "#### IsADirectoryError\n",
    "\n",
    "Levantada quando uma operação de arquivo é executada em um diretório.\n",
    "\n",
    "#### NotADirectoryError\n",
    "\n",
    "Levantada quando uma operação de diretório é executada em algo que não é um diretório.\n",
    "\n",
    "#### PermissionError\n",
    "\n",
    "Levantada quando uma operação não tem as permissões adequadas.\n",
    "\n",
    "#### ProcessLookupError\n",
    "\n",
    "Levantada quando um determinado processo não existe.\n",
    "\n",
    "#### TimeoutError\n",
    "\n",
    "Levantada quando uma função do sistema atinge o tempo limite."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### ReferenceError\n",
    "\n",
    "Esta exceção é levantada quando um intermediário de referência fraca, criado pela função `weakref.proxy()`, é usado para acessar um atributo do referente após ter sido coletado como lixo.\n",
    "\n",
    "### RuntimeError\n",
    "\n",
    "Levantada quando um erro é detectado e não se encaixa em nenhuma das outras categorias. O valor associado é uma string indicando o que precisamente deu errado.\n",
    "\n",
    "#### NotImplementedError\n",
    "\n",
    "Em classes base, definidas pelo usuário, os métodos abstratos devem gerar essa exceção quando requerem que classes derivadas substituam o método, ou enquanto a classe está sendo desenvolvida, para indicar que a implementação real ainda precisa ser adicionada.\n",
    "\n",
    "#### RecursionError\n",
    "\n",
    "É levantada quando o interpretador detecta que a profundidade máxima de recursão foi excedida."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### SyntaxError\n",
    "\n",
    "Levantada quando o analisador encontra um erro de sintaxe. Isso pode ocorrer em uma instrução import, em uma chamada às funções embutidas `compile()`, `exec()` ou `eval()`, ou ao ler o script inicial ou entrada padrão (também interativamente)\n",
    "\n",
    "#### IndentationError\n",
    "\n",
    "Classe base para erros de sintaxe relacionados a indentação incorreta.\n",
    "\n",
    "##### TabError\n",
    "\n",
    "Levantada quando o indentação contém um uso inconsistente de tabulações e espaços.\n",
    "\n",
    "### SystemError\n",
    "\n",
    "Levantada quando o interpretador encontra um erro interno, mas a situação não parece tão grave para fazer com que perca todas as esperanças. O valor associado é uma string que indica o que deu errado (em termos de baixo nível).\n",
    "\n",
    "### TypeError\n",
    "\n",
    "Levantada quando uma operação ou função é aplicada a um objeto de tipo inadequado. O valor associado é uma `string` que fornece detalhes sobre a incompatibilidade de tipo.\n",
    "\n",
    "Essa exceção pode ser levantada pelo código do usuário para indicar que uma tentativa de operação em um objeto não é suportada e não deveria ser. Se um objeto deve ter suporte a uma dada operação, mas ainda não forneceu uma implementação, `NotImplementedError` é a exceção apropriada a ser levantada.\n",
    "\n",
    "Passar argumentos do tipo errado (por exemplo, passar uma `list` quando um `int` é esperado) deve resultar em uma `TypeError`, mas passar argumentos com o valor errado (por exemplo, um número fora limites esperados) deve resultar em um `ValueError`.\n",
    "\n",
    "### ValueError\n",
    "\n",
    "Levantada quando uma operação ou função recebe um argumento que tem o tipo certo, mas um valor inadequado, e a situação não é descrita por uma exceção mais precisa, como `IndexError`."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### UnicodeError\n",
    "\n",
    "Levantada quando ocorre um erro de codificação ou decodificação relacionado ao Unicode.\n",
    "\n",
    "##### UnicodeDecodeError\n",
    "\n",
    "Levantada quando ocorre um erro relacionado ao Unicode durante a codificação.\n",
    "\n",
    "##### UnicodeEncodeError\n",
    "\n",
    "Levantada quando ocorre um erro relacionado ao Unicode durante a decodificação.\n",
    "\n",
    "##### UnicodeTranslateError\n",
    "\n",
    "Levantada quando ocorre um erro relacionado ao Unicode durante a tradução."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Warning\n",
    "\n",
    "Classe base para categorias de aviso.\n",
    "\n",
    "#### DeprecationWarning\n",
    "\n",
    "Classe base para avisos sobre recursos descontinuados quando esses avisos se destinam a outros desenvolvedores Python.\n",
    "\n",
    "#### PendingDeprecationWarning\n",
    "\n",
    "Classe base para avisos sobre recursos que foram descontinuados e devem ser descontinuados no futuro, mas não foram descontinuados ainda.\n",
    "\n",
    "#### RuntimeWarning\n",
    "\n",
    "Classe base para avisos sobre comportamento duvidoso de tempo de execução.\n",
    "\n",
    "#### SyntaxWarning\n",
    "\n",
    "Classe base para avisos sobre sintaxe duvidosa.\n",
    "\n",
    "#### UserWarning\n",
    "\n",
    "Classe base para avisos gerados pelo código do usuário.\n",
    "\n",
    "#### FutureWarning\n",
    "\n",
    "Classe base para avisos sobre recursos descontinuados quando esses avisos se destinam a usuários finais de aplicações escritas em Python.\n",
    "\n",
    "#### ImportWarning\n",
    "\n",
    "Classe base para avisos sobre prováveis erros na importação de módulos.\n",
    "\n",
    "#### UnicodeWarning\n",
    "\n",
    "Classe base para avisos relacionados a Unicode.\n",
    "\n",
    "#### BytesWarning\n",
    "\n",
    "Classe base para avisos relacionados a `bytes` e `bytearray`.\n",
    "\n",
    "#### EncodingWarning\n",
    "\n",
    "Classe base para avisos relacionados a codificações.\n",
    "\n",
    "### ResourceWarning\n",
    "\n",
    "Classe base para avisos relacionados a uso de recursos."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Elevando erros\n",
    "\n",
    "Elevar um erro consiste em voluntariamente executar um erro, para tal nós usamos a keyword `raise`, para os erros nativos podemos passar uma string que servirá de mensagem, a sintaxe seria assim:\n",
    "\n",
    "```python\n",
    "raise TipoDeErro(\"mensagem\")\n",
    "```\n",
    "\n",
    "veja o exemplo:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "Tipo errado de dado",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m/media/Arquivos/Programming/Lessons/PythonLessons/Classes/5-Erros.ipynb Cell 11\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> <a href='vscode-notebook-cell:/media/Arquivos/Programming/Lessons/PythonLessons/Classes/5-Erros.ipynb#X13sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39mraise\u001b[39;00m \u001b[39mTypeError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mTipo errado de dado\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "\u001b[0;31mTypeError\u001b[0m: Tipo errado de dado"
     ]
    }
   ],
   "source": [
    "raise TypeError(\"Tipo errado de dado\")"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Bloco `try-except`\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.5 ('PythonLessons': venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "23b48041b03599eb42c23687325aa4919800bca9a2bdd61183e09a469deba08e"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
